// src/components/ui/radio-button/BTRadioButton.tsx
'use client';
/**
 * BTRadioButton — radio selection atom (Figma 555:3529).
 *
 * Use multiple BTRadioButton with the same modelValue + onChange to build
 * a radio group. Each item selects itself by calling onChange with its value.
 *
 * @example
 * const [selected, setSelected] = useState('a');
 *
 * <BTRadioButton modelValue={selected} value="a" onChange={setSelected} label="Option A" />
 * <BTRadioButton modelValue={selected} value="b" onChange={setSelected} label="Option B" subtext="Helper" />
 * <BTRadioButton modelValue={selected} value="c" onChange={setSelected} label="Disabled" disabled />
 * <BTRadioButton modelValue={selected} value="d" onChange={setSelected} label="Error" error subtext="Error msg" />
 */
import '@/components/ui/radio-button/BTRadioButton.css';
import type { BTRadioButtonProps } from '@/components/ui/radio-button/BTRadioButton.types';

export function BTRadioButton({
  modelValue,
  value,
  onChange,
  label,
  subtext,
  disabled = false,
  error = false,
  name,
  className,
}: BTRadioButtonProps) {
  const isActive = modelValue === value;

  // Mirrors Flutter's `_hasPadding = label != null || subtext != null`.
  // When embedded without label/subtext (e.g. inside BTDropdownList), padding is
  // automatically stripped and the circle centers itself.
  const classes = [
    'bt-radio',
    isActive && 'bt-radio--active',
    disabled && 'bt-radio--disabled',
    error && !disabled && 'bt-radio--error',
    !label && !subtext && 'bt-radio--no-padding',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  function handleChange() {
    if (!disabled) onChange(value);
  }

  return (
    <label className={classes}>
      <input
        className="bt-radio__input"
        type="radio"
        name={name}
        value={String(value)}
        checked={isActive}
        disabled={disabled}
        aria-checked={isActive}
        onChange={handleChange}
      />

      <span className="bt-radio__circle" aria-hidden>
        <span className="bt-radio__dot" />
      </span>

      {(label || subtext) && (
        <span className="bt-radio__text">
          {label && <span className="bt-radio__label">{label}</span>}
          {subtext && <span className="bt-radio__subtext">{subtext}</span>}
        </span>
      )}
    </label>
  );
}

BTRadioButton.displayName = 'BTRadioButton';

// src/components/ui/radio-button/BTRadioButton.vue
<script setup lang="ts">
/**
 * BTRadioButton — radio selection atom (Figma 555:3529).
 *
 * Use multiple BTRadioButton with the same v-model to form a radio group.
 * Each item selects itself when clicked by emitting its own `value`.
 *
 * @example
 * <BTRadioButton v-model="selected" value="a" label="Option A" />
 * <BTRadioButton v-model="selected" value="b" label="Option B" subtext="Helper text" />
 * <BTRadioButton v-model="selected" value="c" label="Option C" disabled />
 * <BTRadioButton v-model="selected" value="d" label="Option D" error subtext="Error message" />
 */
import { computed } from 'vue';
import '@/components/ui/radio-button/BTRadioButton.css';
import type { BTRadioButtonProps } from '@/components/ui/radio-button/BTRadioButton.types';

const props = withDefaults(defineProps<BTRadioButtonProps>(), {
  label: undefined,
  subtext: undefined,
  disabled: false,
  error: false,
  name: undefined,
});

const emit = defineEmits<{
  'update:modelValue': [value: typeof props.value];
}>();

const isActive = computed(() => props.modelValue === props.value);

// Mirrors Flutter's `_hasPadding = label != null || subtext != null`.
// When embedded without label/subtext (e.g. inside BTDropdownList), padding is
// automatically stripped and the circle centers itself.
const classes = computed(() => [
  'bt-radio',
  isActive.value && 'bt-radio--active',
  props.disabled && 'bt-radio--disabled',
  props.error && !props.disabled && 'bt-radio--error',
  !props.label && !props.subtext && 'bt-radio--no-padding',
]);

function handleChange() {
  if (!props.disabled) emit('update:modelValue', props.value);
}
</script>

<template>
  <label :class="classes">
    <input
      class="bt-radio__input"
      type="radio"
      :name="name"
      :value="value"
      :checked="isActive"
      :disabled="disabled"
      :aria-checked="isActive"
      @change="handleChange"
    />

    <span class="bt-radio__circle" aria-hidden="true">
      <span class="bt-radio__dot" />
    </span>

    <span v-if="label || subtext" class="bt-radio__text">
      <span v-if="label" class="bt-radio__label">{{ label }}</span>
      <span v-if="subtext" class="bt-radio__subtext">{{ subtext }}</span>
    </span>
  </label>
</template>
