// src/components/ui/calendar/internal/BTCalendarHeader.vue
<script setup lang="ts">
import { ref, computed, nextTick, watch, onMounted, onBeforeUnmount } from 'vue';
import { positionCentered } from '@/components/ui/calendar/internal/positionFloating';
import BTDropdownList from '@/components/ui/dropdown-list/BTDropdownList.vue';

interface BTCalendarHeaderProps {
  displayDate: Date;
  locale?: string;
  canGoPrev?: boolean;
  canGoNext?: boolean;
}

const props = withDefaults(defineProps<BTCalendarHeaderProps>(), {
  locale: 'id-ID',
  canGoPrev: true,
  canGoNext: true,
});

const emit = defineEmits<{
  prev: [];
  next: [];
  'select-month': [date: Date];
  'select-year': [date: Date];
}>();

// ── Local open state ──────────────────────────────────────────────────────────

const isMonthOpen = ref(false);
const isYearOpen = ref(false);
const monthPillRef = ref<HTMLElement | null>(null);
const yearPillRef = ref<HTMLElement | null>(null);
const monthDropdownRef = ref<HTMLElement | null>(null);
const yearDropdownRef = ref<HTMLElement | null>(null);
const monthDropdownStyle = ref<Record<string, string>>({});
const yearDropdownStyle = ref<Record<string, string>>({});

// Direction for the teleported dropdowns — Teleport-to-body breaks the
// inherited dir="rtl" from the calendar's ancestor, so we set it explicitly
// from the locale.
const dropdownDir = computed<'ltr' | 'rtl'>(() =>
  props.locale.startsWith('ar') ||
  props.locale.startsWith('he') ||
  props.locale.startsWith('iw')
    ? 'rtl'
    : 'ltr',
);

// ── Dropdown items ────────────────────────────────────────────────────────────

const monthItems = computed(() => {
  const year = props.displayDate.getFullYear();
  const current = props.displayDate.getMonth();
  return Array.from({ length: 12 }, (_, i) => ({
    value: String(i),
    label: new Date(year, i, 1).toLocaleDateString(props.locale, { month: 'long' }),
    checked: i === current,
  }));
});

const allYearItems = computed(() => {
  const current = props.displayDate.getFullYear();
  const from = Math.max(1924, current - 100);
  const to = Math.min(2124, current + 100);
  const items = [];
  for (let y = from; y <= to; y++) {
    items.push({ value: String(y), label: String(y), checked: y === current });
  }
  return items;
});

// ── Pill labels ───────────────────────────────────────────────────────────────

const monthLabel = computed(() =>
  props.displayDate.toLocaleDateString(props.locale, { month: 'long' }),
);

// ── Toggle helpers ────────────────────────────────────────────────────────────

// Base style applied before the dropdown is in the DOM (invisible, no top/left yet).
// positionCentered runs in a nextTick watcher once the element is rendered.
const DROPDOWN_BASE: Record<string, string> = {
  position: 'fixed',
  zIndex: '9999',
  minWidth: '160px',
  // invisible until positioned — prevents flash at (0,0)
  opacity: '0',
};

function toggleMonth() {
  if (!isMonthOpen.value) isYearOpen.value = false;
  isMonthOpen.value = !isMonthOpen.value;
}

function toggleYear() {
  if (!isYearOpen.value) isMonthOpen.value = false;
  isYearOpen.value = !isYearOpen.value;
}

// After month dropdown renders: measure and position with smart flip
watch(isMonthOpen, async (open) => {
  if (!open) return;
  monthDropdownStyle.value = { ...DROPDOWN_BASE };
  await nextTick();
  const pill = monthPillRef.value;
  const drop = monthDropdownRef.value;
  if (!pill || !drop) return;
  positionCentered(pill, drop, { gap: 4, margin: 8 });
  monthDropdownStyle.value = { ...DROPDOWN_BASE, opacity: '1' };
});

// After year dropdown renders: measure and position with smart flip
watch(isYearOpen, async (open) => {
  if (!open) return;
  yearDropdownStyle.value = { ...DROPDOWN_BASE };
  await nextTick();
  const pill = yearPillRef.value;
  const drop = yearDropdownRef.value;
  if (!pill || !drop) return;
  positionCentered(pill, drop, { gap: 4, margin: 8 });
  yearDropdownStyle.value = { ...DROPDOWN_BASE, opacity: '1' };
});

// ── Select handlers ───────────────────────────────────────────────────────────

function onMonthSelect(value: string) {
  const monthIndex = parseInt(value, 10);
  const d = new Date(props.displayDate.getFullYear(), monthIndex, 1);
  emit('select-month', d);
  isMonthOpen.value = false;
}

function onYearSelect(value: string) {
  const year = parseInt(value, 10);
  const d = new Date(year, props.displayDate.getMonth(), 1);
  emit('select-year', d);
  isYearOpen.value = false;
}

// ── Click outside ─────────────────────────────────────────────────────────────

function onClickOutside(e: MouseEvent) {
  const target = e.target as Node;
  const insideMonth =
    monthPillRef.value?.contains(target) || monthDropdownRef.value?.contains(target);
  const insideYear =
    yearPillRef.value?.contains(target) || yearDropdownRef.value?.contains(target);
  if (!insideMonth) isMonthOpen.value = false;
  if (!insideYear) isYearOpen.value = false;
}

// Recompute position on scroll so the dropdown tracks its pill as the page scrolls.
function onScrollOrResize() {
  if (isMonthOpen.value && monthPillRef.value && monthDropdownRef.value) {
    positionCentered(monthPillRef.value, monthDropdownRef.value, { gap: 4, margin: 8 });
  }
  if (isYearOpen.value && yearPillRef.value && yearDropdownRef.value) {
    positionCentered(yearPillRef.value, yearDropdownRef.value, { gap: 4, margin: 8 });
  }
}

onMounted(() => {
  document.addEventListener('click', onClickOutside);
  window.addEventListener('scroll', onScrollOrResize, true);
  window.addEventListener('resize', onScrollOrResize);
});

onBeforeUnmount(() => {
  document.removeEventListener('click', onClickOutside);
  window.removeEventListener('scroll', onScrollOrResize, true);
  window.removeEventListener('resize', onScrollOrResize);
});
</script>

<template>
  <div class="bt-calendar__header">
    <!-- Left nav -->
    <button
      class="bt-calendar__nav-btn"
      type="button"
      :disabled="!canGoPrev"
      aria-label="Bulan sebelumnya"
      @click="emit('prev')"
    >
      <svg
        width="16"
        height="16"
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        <path
          d="M10 4L6 8L10 12"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>

    <!-- Month + year pills -->
    <div class="bt-calendar__header-labels">

      <!-- Month pill + dropdown -->
      <div ref="monthPillRef" class="bt-calendar__pill-wrapper">
        <button
          class="bt-calendar__header-pill"
          type="button"
          :aria-expanded="isMonthOpen"
          @click="toggleMonth"
        >
          {{ monthLabel }}
          <svg
            class="bt-calendar__header-arrow"
            :class="{ 'bt-calendar__header-arrow--open': isMonthOpen }"
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            aria-hidden="true"
          >
            <path
              d="M4 6L8 10L12 6"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </button>

        <Teleport to="body">
          <div v-if="isMonthOpen" ref="monthDropdownRef" :style="monthDropdownStyle" :dir="dropdownDir" data-bt-calendar-dropdown>
            <BTDropdownList
              variant="radio"
              :items="monthItems"
              @select="onMonthSelect"
            />
          </div>
        </Teleport>
      </div>

      <!-- Year pill + dropdown -->
      <div ref="yearPillRef" class="bt-calendar__pill-wrapper">
        <button
          class="bt-calendar__header-pill"
          type="button"
          :aria-expanded="isYearOpen"
          @click="toggleYear"
        >
          {{ displayDate.getFullYear() }}
          <svg
            class="bt-calendar__header-arrow"
            :class="{ 'bt-calendar__header-arrow--open': isYearOpen }"
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            aria-hidden="true"
          >
            <path
              d="M4 6L8 10L12 6"
              stroke="currentColor"
              stroke-width="1.5"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </button>

        <Teleport to="body">
          <div v-if="isYearOpen" ref="yearDropdownRef" :style="yearDropdownStyle" :dir="dropdownDir" data-bt-calendar-dropdown>
            <BTDropdownList
              variant="radio"
              :items="allYearItems"
              @select="onYearSelect"
            />
          </div>
        </Teleport>
      </div>
    </div>

    <!-- Right nav -->
    <button
      class="bt-calendar__nav-btn"
      type="button"
      :disabled="!canGoNext"
      aria-label="Bulan berikutnya"
      @click="emit('next')"
    >
      <svg
        width="16"
        height="16"
        viewBox="0 0 16 16"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true"
      >
        <path
          d="M6 4L10 8L6 12"
          stroke="currentColor"
          stroke-width="1.5"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>
  </div>
</template>

// src/components/ui/calendar/internal/BTCalendarHeader.tsx
'use client';
import { useState, useRef, useEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { BTDropdownList } from '@/components/ui/dropdown-list/BTDropdownList';

interface BTCalendarHeaderProps {
  displayDate: Date;
  locale?: string;
  canGoPrev?: boolean;
  canGoNext?: boolean;
  onPrev: () => void;
  onNext: () => void;
  onSelectMonth: (date: Date) => void;
  onSelectYear: (date: Date) => void;
}

export function BTCalendarHeader({
  displayDate,
  locale = 'id-ID',
  canGoPrev = true,
  canGoNext = true,
  onPrev,
  onNext,
  onSelectMonth,
  onSelectYear,
}: BTCalendarHeaderProps) {
  const [isMonthOpen, setIsMonthOpen] = useState(false);
  const [isYearOpen, setIsYearOpen] = useState(false);
  const [monthDropdownStyle, setMonthDropdownStyle] = useState<React.CSSProperties>({});
  const [yearDropdownStyle, setYearDropdownStyle] = useState<React.CSSProperties>({});
  const monthPillRef = useRef<HTMLDivElement>(null);
  const yearPillRef = useRef<HTMLDivElement>(null);
  const monthDropdownRef = useRef<HTMLDivElement>(null);
  const yearDropdownRef = useRef<HTMLDivElement>(null);

  // Teleporting to body loses the inherited dir="rtl" from the calendar's
  // ancestor — set it explicitly from the locale.
  const dropdownDir: 'ltr' | 'rtl' =
    locale.startsWith('ar') ||
    locale.startsWith('he') ||
    locale.startsWith('iw')
      ? 'rtl'
      : 'ltr';

  // ── Dropdown items ──────────────────────────────────────────────────────────

  const monthItems = useMemo(() => {
    const year = displayDate.getFullYear();
    const current = displayDate.getMonth();
    return Array.from({ length: 12 }, (_, i) => ({
      value: String(i),
      label: new Date(year, i, 1).toLocaleDateString(locale, { month: 'long' }),
      checked: i === current,
    }));
  }, [displayDate, locale]);

  const allYearItems = useMemo(() => {
    const current = displayDate.getFullYear();
    const from = Math.max(1924, current - 100);
    const to = Math.min(2124, current + 100);
    const items = [];
    for (let y = from; y <= to; y++) {
      items.push({ value: String(y), label: String(y), checked: y === current });
    }
    return items;
  }, [displayDate]);

  const monthLabel = displayDate.toLocaleDateString(locale, { month: 'long' });

  // ── Position helpers ────────────────────────────────────────────────────────

  function computeStyle(el: HTMLElement | null): React.CSSProperties {
    if (!el) return {};
    const rect = el.getBoundingClientRect();
    return {
      position: 'fixed',
      top: rect.bottom + 4,
      left: rect.left + rect.width / 2,
      transform: 'translateX(-50%)',
      zIndex: 9999,
      minWidth: 160,
    };
  }

  // ── Toggle handlers ─────────────────────────────────────────────────────────

  function toggleMonth() {
    if (!isMonthOpen) {
      setMonthDropdownStyle(computeStyle(monthPillRef.current));
      setIsYearOpen(false);
    }
    setIsMonthOpen((v) => !v);
  }

  function toggleYear() {
    if (!isYearOpen) {
      setYearDropdownStyle(computeStyle(yearPillRef.current));
      setIsMonthOpen(false);
    }
    setIsYearOpen((v) => !v);
  }

  // ── Select handlers ─────────────────────────────────────────────────────────

  function handleMonthSelect(value: string) {
    const monthIndex = parseInt(value, 10);
    onSelectMonth(new Date(displayDate.getFullYear(), monthIndex, 1));
    setIsMonthOpen(false);
  }

  function handleYearSelect(value: string) {
    const year = parseInt(value, 10);
    onSelectYear(new Date(year, displayDate.getMonth(), 1));
    setIsYearOpen(false);
  }

  // ── Click outside ───────────────────────────────────────────────────────────

  useEffect(() => {
    function onClickOutside(e: MouseEvent) {
      const target = e.target as Node;
      const insideMonth =
        monthPillRef.current?.contains(target) || monthDropdownRef.current?.contains(target);
      const insideYear =
        yearPillRef.current?.contains(target) || yearDropdownRef.current?.contains(target);
      if (!insideMonth) setIsMonthOpen(false);
      if (!insideYear) setIsYearOpen(false);
    }
    document.addEventListener('click', onClickOutside);
    return () => document.removeEventListener('click', onClickOutside);
  }, []);

  // Recompute position on scroll/resize so the dropdown tracks its pill.
  useEffect(() => {
    function onScrollOrResize() {
      setMonthDropdownStyle((prev) =>
        Object.keys(prev).length ? computeStyle(monthPillRef.current) : prev,
      );
      setYearDropdownStyle((prev) =>
        Object.keys(prev).length ? computeStyle(yearPillRef.current) : prev,
      );
    }
    window.addEventListener('scroll', onScrollOrResize, true);
    window.addEventListener('resize', onScrollOrResize);
    return () => {
      window.removeEventListener('scroll', onScrollOrResize, true);
      window.removeEventListener('resize', onScrollOrResize);
    };
  }, []);

  // ── Render ──────────────────────────────────────────────────────────────────

  return (
    <div className="bt-calendar__header">
      {/* Left nav */}
      <button
        className="bt-calendar__nav-btn"
        type="button"
        disabled={!canGoPrev}
        aria-label="Bulan sebelumnya"
        onClick={onPrev}
      >
        <svg
          width="16"
          height="16"
          viewBox="0 0 16 16"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          aria-hidden="true"
        >
          <path
            d="M10 4L6 8L10 12"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </button>

      {/* Month + year pills */}
      <div className="bt-calendar__header-labels">

        {/* Month pill + dropdown */}
        <div ref={monthPillRef} className="bt-calendar__pill-wrapper">
          <button
            className="bt-calendar__header-pill"
            type="button"
            aria-expanded={isMonthOpen}
            onClick={toggleMonth}
          >
            {monthLabel}
            <svg
              className={`bt-calendar__header-arrow${isMonthOpen ? ' bt-calendar__header-arrow--open' : ''}`}
              width="16"
              height="16"
              viewBox="0 0 16 16"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
            >
              <path
                d="M4 6L8 10L12 6"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </button>

          {isMonthOpen && createPortal(
            <div ref={monthDropdownRef} style={monthDropdownStyle} dir={dropdownDir}>
              <BTDropdownList
                variant="radio"
                items={monthItems}
                onSelect={handleMonthSelect}
              />
            </div>,
            document.body,
          )}
        </div>

        {/* Year pill + dropdown */}
        <div ref={yearPillRef} className="bt-calendar__pill-wrapper">
          <button
            className="bt-calendar__header-pill"
            type="button"
            aria-expanded={isYearOpen}
            onClick={toggleYear}
          >
            {displayDate.getFullYear()}
            <svg
              className={`bt-calendar__header-arrow${isYearOpen ? ' bt-calendar__header-arrow--open' : ''}`}
              width="16"
              height="16"
              viewBox="0 0 16 16"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              aria-hidden="true"
            >
              <path
                d="M4 6L8 10L12 6"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </button>

          {isYearOpen && createPortal(
            <div ref={yearDropdownRef} style={yearDropdownStyle} dir={dropdownDir}>
              <BTDropdownList
                variant="radio"
                items={allYearItems}
                onSelect={handleYearSelect}
              />
            </div>,
            document.body,
          )}
        </div>
      </div>

      {/* Right nav */}
      <button
        className="bt-calendar__nav-btn"
        type="button"
        disabled={!canGoNext}
        aria-label="Bulan berikutnya"
        onClick={onNext}
      >
        <svg
          width="16"
          height="16"
          viewBox="0 0 16 16"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          aria-hidden="true"
        >
          <path
            d="M6 4L10 8L6 12"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </button>
    </div>
  );
}

BTCalendarHeader.displayName = 'BTCalendarHeader';
