// src/components/ui/modal/BTModal.vue
<script setup lang="ts">
/**
 * BTModal — centred dialog with backdrop, header, optional content, footer.
 *
 * Figma: D-Modal 2123:1992 (web) · M-Modal 2124:2190 (mobile).
 *
 * @example
 * ```vue
 * <BTModal
 *   v-model:open="open"
 *   title="Confirm action"
 *   subtext="Are you sure you want to continue?"
 *   size="md"
 *   @primary="open = false"
 *   @secondary="open = false"
 * >
 *   <p>Optional content goes here.</p>
 * </BTModal>
 * ```
 */
import { computed, ref, useSlots, watch } from 'vue';
import '@/components/ui/modal/BTModal.css';
import type { BTModalProps } from '@/components/ui/modal/BTModal.types';
import BTButton from '@/components/ui/button/BTButton.vue';

const props = withDefaults(defineProps<BTModalProps>(), {
  size: 'sm',
  hasClose: true,
  hasFooter: true,
  primaryLabel: 'Confirm',
  hasSecondaryButton: true,
  secondaryLabel: 'Cancel',
  hasCheckbox: false,
  checkboxLabel: "Don't show again",
  dismissable: true,
});

const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
  (e: 'primary'): void;
  (e: 'secondary'): void;
  (e: 'close'): void;
  (e: 'checkbox', checked: boolean): void;
}>();

const slots = useSlots();
const checked = ref(false);

const panelClass = computed(() => `bt-modal-panel bt-modal-panel--${props.size}`);

function close(): void {
  emit('update:open', false);
  emit('close');
}

function backdropClick(): void {
  if (props.dismissable) close();
}

function onPrimary(): void {
  emit('primary');
}

function onSecondary(): void {
  emit('secondary');
}

function onCheckboxChange(e: Event): void {
  const target = e.target as HTMLInputElement;
  checked.value = target.checked;
  emit('checkbox', target.checked);
}

// ── Body scroll lock ───────────────────────────────────────────────────────
watch(
  () => props.open,
  (isOpen) => {
    if (typeof document === 'undefined') return;
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
  },
  { immediate: true },
);
</script>

<template>
  <Teleport to="body">
    <Transition name="bt-modal">
      <div
        v-if="open"
        class="bt-modal-backdrop"
        @click.self="backdropClick"
      >
        <div :class="panelClass" role="dialog" aria-modal="true">
          <!-- Header -->
          <div class="bt-modal-header">
            <h2 class="bt-modal-title">{{ title }}</h2>
            <p v-if="subtext" class="bt-modal-subtext">{{ subtext }}</p>
            <button
              v-if="hasClose"
              type="button"
              class="bt-modal-close"
              aria-label="Close"
              @click="close"
            >
              <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true">
                <path
                  d="M3.5 3.5 L12.5 12.5 M12.5 3.5 L3.5 12.5"
                  stroke="currentColor"
                  stroke-width="1.6"
                  stroke-linecap="round"
                />
              </svg>
            </button>
          </div>

          <!-- Optional content -->
          <div v-if="slots.default" class="bt-modal-content">
            <slot />
          </div>

          <!-- Footer -->
          <div v-if="hasFooter" class="bt-modal-footer">
            <div v-if="hasCheckbox" class="bt-modal-footer__left">
              <input
                id="bt-modal-checkbox"
                type="checkbox"
                class="bt-modal-footer__checkbox"
                :checked="checked"
                @change="onCheckboxChange"
              >
              <label for="bt-modal-checkbox" class="bt-modal-footer__checkbox-label">
                {{ checkboxLabel }}
              </label>
            </div>
            <BTButton
              v-if="hasSecondaryButton"
              variant="secondary-light"
              :label="secondaryLabel"
              @click="onSecondary"
            />
            <BTButton
              :label="primaryLabel"
              @click="onPrimary"
            />
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

// src/components/ui/modal/BTModal.tsx
'use client';
/**
 * BTModal — centred dialog with backdrop, header, optional content, footer.
 *
 * Figma: D-Modal 2123:1992 (web) · M-Modal 2124:2190 (mobile).
 *
 * @example
 * ```tsx
 * import { useState } from 'react';
 * import { BTModal } from '@btech/ui-react';
 *
 * export function Example() {
 *   const [open, setOpen] = useState(false);
 *   return (
 *     <>
 *       <button onClick={() => setOpen(true)}>Open</button>
 *       <BTModal
 *         open={open}
 *         title="Confirm action"
 *         subtext="Are you sure you want to continue?"
 *         size="md"
 *         onPrimary={() => setOpen(false)}
 *         onSecondary={() => setOpen(false)}
 *         onClose={() => setOpen(false)}
 *       >
 *         <p>Optional content goes here.</p>
 *       </BTModal>
 *     </>
 *   );
 * }
 * ```
 */
import { useEffect, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import '@/components/ui/modal/BTModal.css';
import type { BTModalProps } from '@/components/ui/modal/BTModal.types';
import { BTButton } from '@/components/ui/button/BTButton';

interface BTModalReactProps extends BTModalProps {
  children?: ReactNode;
  onPrimary?: () => void;
  onSecondary?: () => void;
  onClose?: () => void;
  onCheckbox?: (checked: boolean) => void;
}

export function BTModal({
  open,
  title,
  subtext,
  size = 'sm',
  hasClose = true,
  hasFooter = true,
  primaryLabel = 'Confirm',
  hasSecondaryButton = true,
  secondaryLabel = 'Cancel',
  hasCheckbox = false,
  checkboxLabel = "Don't show again",
  dismissable = true,
  children,
  onPrimary,
  onSecondary,
  onClose,
  onCheckbox,
}: BTModalReactProps) {
  const [checked, setChecked] = useState(false);

  // ── Body scroll lock ─────────────────────────────────────────────────────
  useEffect(() => {
    if (typeof document === 'undefined') return;
    if (open) {
      const prev = document.body.style.overflow;
      document.body.style.overflow = 'hidden';
      return () => {
        document.body.style.overflow = prev;
      };
    }
    return undefined;
  }, [open]);

  if (!open) return null;
  if (typeof document === 'undefined') return null;

  const close = (): void => {
    onClose?.();
  };

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>): void => {
    if (e.target !== e.currentTarget) return;
    if (dismissable) close();
  };

  const handleCheckboxChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    setChecked(e.target.checked);
    onCheckbox?.(e.target.checked);
  };

  return createPortal(
    <div
      className="bt-modal-backdrop bt-modal-backdrop--animated"
      onClick={handleBackdropClick}
    >
      <div className={`bt-modal-panel bt-modal-panel--${size}`} role="dialog" aria-modal="true">
        {/* Header */}
        <div className="bt-modal-header">
          <h2 className="bt-modal-title">{title}</h2>
          {subtext && <p className="bt-modal-subtext">{subtext}</p>}
          {hasClose && (
            <button
              type="button"
              className="bt-modal-close"
              aria-label="Close"
              onClick={close}
            >
              <svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true">
                <path
                  d="M3.5 3.5 L12.5 12.5 M12.5 3.5 L3.5 12.5"
                  stroke="currentColor"
                  strokeWidth="1.6"
                  strokeLinecap="round"
                />
              </svg>
            </button>
          )}
        </div>

        {/* Optional content */}
        {children && <div className="bt-modal-content">{children}</div>}

        {/* Footer */}
        {hasFooter && (
          <div className="bt-modal-footer">
            {hasCheckbox && (
              <div className="bt-modal-footer__left">
                <input
                  id="bt-modal-checkbox"
                  type="checkbox"
                  className="bt-modal-footer__checkbox"
                  checked={checked}
                  onChange={handleCheckboxChange}
                />
                <label htmlFor="bt-modal-checkbox" className="bt-modal-footer__checkbox-label">
                  {checkboxLabel}
                </label>
              </div>
            )}
            {hasSecondaryButton && (
              <BTButton
                variant="secondary-light"
                label={secondaryLabel}
                onClick={() => onSecondary?.()}
              />
            )}
            <BTButton
              label={primaryLabel}
              onClick={() => onPrimary?.()}
            />
          </div>
        )}
      </div>
    </div>,
    document.body,
  );
}
