// src/components/ui/tooltip/BTTooltip.tsx
'use client';
/**
 * BTTooltip — hover tooltip wrapping a trigger element.
 *
 * Figma: https://www.figma.com/design/WANr9drWYNYbMPuT2sMeHi/?node-id=479-2624
 *
 * @example
 * ```tsx
 * <BTTooltip text="Klik untuk menyimpan" position="top">
 *   <BTButton>Simpan</BTButton>
 * </BTTooltip>
 *
 * // Rich content
 * <BTTooltip position="bottom" arrowPosition="left" content={<strong>Bold tip</strong>}>
 *   <span>Hover me</span>
 * </BTTooltip>
 * ```
 */
import {
  useState,
  useRef,
  useCallback,
  useEffect,
  type ReactNode,
  type MouseEvent,
  type FocusEvent,
} from 'react';
import { createPortal } from 'react-dom';
import type { BTTooltipPosition, BTTooltipArrowPosition } from '@/components/ui/tooltip/BTTooltip.types';
import '@/components/ui/tooltip/BTTooltip.css';

export interface BTTooltipReactProps {
  /** Plain-text content. Use `content` prop for rich JSX. */
  text?: string;
  /** Rich JSX content — overrides `text`. */
  content?: ReactNode;
  /** Preferred placement relative to trigger. @default 'top' */
  position?: BTTooltipPosition;
  /** Arrow offset along the axis. @default 'mid' */
  arrowPosition?: BTTooltipArrowPosition;
  /** Disable tooltip. @default false */
  disabled?: boolean;
  /** Delay before show (ms). @default 0 */
  showDelay?: number;
  /** Delay before hide (ms). @default 0 */
  hideDelay?: number;
  /** Removes min-width so the body shrinks to content width.
   *  Use for short labels (e.g. collapsed sidebar item names). @default false */
  compact?: boolean;
  /** Controlled visibility — when set, hover/focus is ignored. */
  visible?: boolean;
  /** Trigger element (required). */
  children: ReactNode;
  /** Called when the tooltip becomes visible. */
  onShow?: () => void;
  /** Called when the tooltip hides. */
  onHide?: () => void;
}

const GAP = 4;

function getArrowPath(position: BTTooltipPosition): string {
  switch (position) {
    case 'bottom': return 'M0 8 L7 1 Q8 0 9 1 L16 8 Z';
    case 'left':   return 'M0 0 L7 7 Q8 8 7 9 L0 16 Z';
    case 'right':  return 'M8 0 L1 7 Q0 8 1 9 L8 16 Z';
    case 'top':
    default:       return 'M0 0 L7 7 Q8 8 9 7 L16 0 Z';
  }
}

export function BTTooltip({
  text,
  content,
  position = 'top',
  arrowPosition = 'mid',
  disabled = false,
  showDelay = 0,
  hideDelay = 0,
  compact = false,
  visible,
  children,
  onShow,
  onHide,
}: BTTooltipReactProps) {
  const [isVisible, setIsVisible] = useState(false);
  const isControlled = visible !== undefined;
  const effectiveVisible = isControlled ? !!visible : isVisible;
  const triggerRef = useRef<HTMLDivElement>(null);
  const balloonRef = useRef<HTMLDivElement>(null);
  const showTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const hideTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const isHorizontal = position === 'left' || position === 'right';
  const arrowPath = getArrowPath(position);
  const arrowViewBox = isHorizontal ? '0 0 8 16' : '0 0 16 8';
  const arrowW = isHorizontal ? 8 : 16;
  const arrowH = isHorizontal ? 16 : 8;

  const updatePosition = useCallback(() => {
    const trigger = triggerRef.current;
    const balloon = balloonRef.current;
    if (!trigger || !balloon) return;

    const tr = trigger.getBoundingClientRect();
    const bw = balloon.offsetWidth;
    const bh = balloon.offsetHeight;
    const vw = window.innerWidth;
    const vh = window.innerHeight;

    // Trigger centre coords (for arrow alignment)
    const tcx = tr.left + tr.width / 2;
    const tcy = tr.top + tr.height / 2;

    let top = 0;
    let left = 0;

    switch (position) {
      case 'bottom':
        top = tr.bottom + GAP;
        left = tcx - bw / 2;
        break;
      case 'left':
        top = tcy - bh / 2;
        left = tr.left - bw - GAP;
        break;
      case 'right':
        top = tcy - bh / 2;
        left = tr.right + GAP;
        break;
      case 'top':
      default:
        top = tr.top - bh - GAP;
        left = tcx - bw / 2;
        break;
    }

    left = Math.max(8, Math.min(left, vw - bw - 8));
    top = Math.max(8, Math.min(top, vh - bh - 8));

    balloon.style.top = `${top}px`;
    balloon.style.left = `${left}px`;

    // Dynamic arrow offset: px from balloon edge to trigger centre
    const arrowOffset =
      (position === 'left' || position === 'right')
        ? tcy - top
        : tcx - left;
    balloon.style.setProperty('--bt-arrow-offset', `${arrowOffset}px`);
  }, [position]);

  const show = useCallback(() => {
    if (disabled || isControlled) return;
    if (hideTimerRef.current) { clearTimeout(hideTimerRef.current); hideTimerRef.current = null; }
    showTimerRef.current = setTimeout(() => {
      setIsVisible(true);
      onShow?.();
    }, showDelay);
  }, [disabled, showDelay, onShow]);

  const hide = useCallback(() => {
    if (isControlled) return;
    if (showTimerRef.current) { clearTimeout(showTimerRef.current); showTimerRef.current = null; }
    hideTimerRef.current = setTimeout(() => {
      setIsVisible(false);
      onHide?.();
    }, hideDelay);
  }, [isControlled, hideDelay, onHide]);

  const dismiss = useCallback(() => {
    if (isControlled) return;
    if (showTimerRef.current) { clearTimeout(showTimerRef.current); showTimerRef.current = null; }
    if (hideTimerRef.current) { clearTimeout(hideTimerRef.current); hideTimerRef.current = null; }
    setIsVisible(false);
    onHide?.();
  }, [isControlled, onHide]);

  // Update position after balloon becomes visible (hover or controlled).
  useEffect(() => {
    if (effectiveVisible) {
      // Double-rAF to ensure DOM is fully painted with new height
      requestAnimationFrame(() => requestAnimationFrame(updatePosition));
    }
  }, [effectiveVisible, updatePosition]);

  // Controlled mode: fire show/hide callbacks as the prop flips.
  useEffect(() => {
    if (!isControlled) return;
    if (visible) onShow?.();
    else onHide?.();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isControlled, visible]);

  useEffect(() => {
    return () => {
      if (showTimerRef.current) clearTimeout(showTimerRef.current);
      if (hideTimerRef.current) clearTimeout(hideTimerRef.current);
    };
  }, []);

  useEffect(() => {
    if (isControlled) return;

    const onScroll = () => dismiss();
    document.addEventListener('scroll', onScroll, true);
    return () => document.removeEventListener('scroll', onScroll, true);
  }, [dismiss, isControlled]);

  const balloonClass = [
    'bt-tooltip__balloon',
    `bt-tooltip__balloon--${position}`,
    effectiveVisible ? 'bt-tooltip__balloon--visible' : '',
    compact ? 'bt-tooltip__balloon--compact' : '',
    // Controlled tooltips are decorative — never steal the pointer (would
    // otherwise cause flicker when the balloon overlaps the trigger area).
    isControlled ? 'bt-tooltip__balloon--passthrough' : '',
  ].filter(Boolean).join(' ');

  // Arrow wrappers use no modifier classes — offset set via --bt-arrow-offset in updatePosition
  const arrowRowClass = 'bt-tooltip__arrow-row';
  const arrowColClass = 'bt-tooltip__arrow-col';

  const arrowSvg = (
    <svg
      className="bt-tooltip__arrow"
      width={arrowW}
      height={arrowH}
      viewBox={arrowViewBox}
      fill="none"
      aria-hidden="true"
    >
      <path d={arrowPath} fill="var(--bg-inverse)" />
    </svg>
  );

  return (
    <div
      ref={triggerRef}
      className="bt-tooltip"
      onMouseEnter={show}
      onMouseLeave={hide}
      onFocus={(_e: FocusEvent) => show()}
      onBlur={(_e: FocusEvent) => hide()}
    >
      {children}

      {createPortal(
        <div ref={balloonRef} className={balloonClass} role="tooltip" aria-live="polite">
          {/* Arrow */}
          {!isHorizontal ? (
            <div className={arrowRowClass}>{arrowSvg}</div>
          ) : (
            <div className={arrowColClass}>{arrowSvg}</div>
          )}

          {/* Body */}
          <div className="bt-tooltip__body">
            {content ?? (text ? <p className="bt-tooltip__text">{text}</p> : null)}
          </div>
        </div>,
        document.body,
      )}
    </div>
  );
}

// src/components/ui/tooltip/BTTooltip.vue
<script setup lang="ts">
/**
 * BTTooltip — hover tooltip wrapping a trigger element.
 *
 * Figma: https://www.figma.com/design/WANr9drWYNYbMPuT2sMeHi/?node-id=479-2624
 *
 * @example
 * ```vue
 * <BTTooltip text="Klik untuk menyimpan" position="top">
 *   <BTButton>Simpan</BTButton>
 * </BTTooltip>
 *
 * <!-- Rich content slot -->
 * <BTTooltip position="bottom" arrow-position="left">
 *   <template #trigger><BTButton>Info</BTButton></template>
 *   <template #content>
 *     <strong>Custom</strong> content here.
 *   </template>
 * </BTTooltip>
 * ```
 */
import { ref, computed, nextTick, onMounted, onUnmounted, watch } from 'vue';
import type { BTTooltipPosition, BTTooltipArrowPosition } from '@/components/ui/tooltip/BTTooltip.types';
import '@/components/ui/tooltip/BTTooltip.css';

const props = withDefaults(
  defineProps<{
    text?: string;
    position?: BTTooltipPosition;
    arrowPosition?: BTTooltipArrowPosition;
    disabled?: boolean;
    showDelay?: number;
    hideDelay?: number;
    /** When true, removes the min-width constraint so the body shrinks to content width.
     *  Use for short labels (e.g. collapsed sidebar item names). */
    compact?: boolean;
    /** Controlled visibility — when set, hover/focus is ignored. */
    visible?: boolean;
  }>(),
  {
    position: 'top',
    arrowPosition: 'mid',
    disabled: false,
    showDelay: 0,
    hideDelay: 0,
    compact: false,
    visible: undefined,
  },
);

/** True when the parent drives visibility via the `visible` prop. */
const isControlled = computed(() => props.visible !== undefined);
/** The actual visibility used for rendering (controlled prop or hover state). */
const effectiveVisible = computed(() =>
  isControlled.value ? !!props.visible : isVisible.value,
);

const emit = defineEmits<{
  (e: 'show'): void;
  (e: 'hide'): void;
}>();

// ── State ──────────────────────────────────────────────────────────────────

const triggerRef = ref<HTMLElement | null>(null);
const balloonRef = ref<HTMLElement | null>(null);
const isVisible = ref(false);

let showTimer: ReturnType<typeof setTimeout> | null = null;
let hideTimer: ReturnType<typeof setTimeout> | null = null;

// ── Positioning ────────────────────────────────────────────────────────────

const GAP = 4; // px between trigger edge and balloon

/**
 * Positions the balloon so that its arrow points at the trigger's centre,
 * then clamps the balloon to the viewport.  After clamping, --bt-arrow-offset
 * is updated to the actual px distance from the balloon edge to the trigger
 * centre, so the arrow always points accurately even when the balloon is
 * clamped near a viewport edge.
 */
function updatePosition(): void {
  const trigger = triggerRef.value;
  const balloon = balloonRef.value;
  if (!trigger || !balloon) return;

  const tr = trigger.getBoundingClientRect();
  const bw = balloon.offsetWidth;
  const bh = balloon.offsetHeight;
  const vw = window.innerWidth;
  const vh = window.innerHeight;

  // Trigger centre coords (for arrow alignment)
  const tcx = tr.left + tr.width / 2;
  const tcy = tr.top + tr.height / 2;

  let top = 0;
  let left = 0;

  switch (props.position) {
    case 'bottom':
      top = tr.bottom + GAP;
      left = tcx - bw / 2; // centre balloon on trigger
      break;
    case 'left':
      top = tcy - bh / 2;
      left = tr.left - bw - GAP;
      break;
    case 'right':
      top = tcy - bh / 2;
      left = tr.right + GAP;
      break;
    case 'top':
    default:
      top = tr.top - bh - GAP;
      left = tcx - bw / 2; // centre balloon on trigger
      break;
  }

  // Viewport clamping
  left = Math.max(8, Math.min(left, vw - bw - 8));
  top = Math.max(8, Math.min(top, vh - bh - 8));

  balloon.style.top = `${top}px`;
  balloon.style.left = `${left}px`;

  // Dynamic arrow offset: px from balloon edge to trigger centre
  const arrowOffset =
    (props.position === 'left' || props.position === 'right')
      ? tcy - top  // vertical arrow: from top edge to trigger centre Y
      : tcx - left; // horizontal arrow: from left edge to trigger centre X
  balloon.style.setProperty('--bt-arrow-offset', `${arrowOffset}px`);
}

// ── Visibility ─────────────────────────────────────────────────────────────

function show(): void {
  if (props.disabled || isControlled.value) return;
  if (hideTimer) { clearTimeout(hideTimer); hideTimer = null; }
  showTimer = setTimeout(async () => {
    isVisible.value = true;
    await nextTick();
    updatePosition();
    emit('show');
  }, props.showDelay);
}

function hide(): void {
  if (isControlled.value) return;
  if (showTimer) { clearTimeout(showTimer); showTimer = null; }
  hideTimer = setTimeout(() => {
    isVisible.value = false;
    emit('hide');
  }, props.hideDelay);
}

function dismiss(): void {
  if (isControlled.value) return;
  if (showTimer) { clearTimeout(showTimer); showTimer = null; }
  if (hideTimer) { clearTimeout(hideTimer); hideTimer = null; }
  isVisible.value = false;
  emit('hide');
}

// Controlled mode: reposition on show, emit show/hide as the prop flips.
// Declared here (after updatePosition / emit) so the immediate run is safe.
watch(
  () => props.visible,
  async (v) => {
    if (!isControlled.value) return;
    if (v) {
      await nextTick();
      updatePosition();
      emit('show');
    } else {
      emit('hide');
    }
  },
  { immediate: true },
);

onUnmounted(() => {
  if (showTimer) clearTimeout(showTimer);
  if (hideTimer) clearTimeout(hideTimer);
  document.removeEventListener('scroll', onScroll, true);
});

function onScroll(): void {
  dismiss();
}

onMounted(() => {
  if (isControlled.value) return;
  document.addEventListener('scroll', onScroll, true);
});

// ── Arrow SVG paths ────────────────────────────────────────────────────────

/** SVG path for the arrow, facing the trigger (pointing away from body). */
const arrowPath = computed<string>(() => {
  // All arrows: 16×8 (horizontal) or 8×16 (vertical).
  // Slightly rounded tip via quadratic bezier.
  switch (props.position) {
    case 'bottom': // arrow at top of balloon, pointing up toward trigger
      return 'M0 8 L7 1 Q8 0 9 1 L16 8 Z';
    case 'left':   // arrow at right of balloon, pointing right toward trigger
      return 'M0 0 L7 7 Q8 8 7 9 L0 16 Z';
    case 'right':  // arrow at left of balloon, pointing left toward trigger
      return 'M8 0 L1 7 Q0 8 1 9 L8 16 Z';
    case 'top':    // arrow at bottom of balloon, pointing down toward trigger
    default:
      return 'M0 0 L7 7 Q8 8 9 7 L16 0 Z';
  }
});

const arrowViewBox = computed<string>(() =>
  props.position === 'left' || props.position === 'right' ? '0 0 8 16' : '0 0 16 8',
);

const arrowWidth = computed<number>(() =>
  props.position === 'left' || props.position === 'right' ? 8 : 16,
);

const arrowHeight = computed<number>(() =>
  props.position === 'left' || props.position === 'right' ? 16 : 8,
);

const isHorizontalPosition = computed(() =>
  props.position === 'left' || props.position === 'right',
);

const balloonClasses = computed(() => [
  'bt-tooltip__balloon',
  `bt-tooltip__balloon--${props.position}`,
  effectiveVisible.value ? 'bt-tooltip__balloon--visible' : '',
  props.compact ? 'bt-tooltip__balloon--compact' : '',
  // Controlled tooltips are decorative — never steal the pointer (would
  // otherwise cause flicker when the balloon overlaps the trigger area).
  isControlled.value ? 'bt-tooltip__balloon--passthrough' : '',
]);

// Arrow wrappers no longer need position-modifier classes — offset is
// set dynamically via --bt-arrow-offset in updatePosition().
const arrowRowClass = 'bt-tooltip__arrow-row';
const arrowColClass = 'bt-tooltip__arrow-col';
</script>

<template>
  <div
    ref="triggerRef"
    class="bt-tooltip"
    @mouseenter="show"
    @mouseleave="hide"
    @focusin="show"
    @focusout="hide"
  >
    <!-- Trigger -->
    <slot />

    <!-- Floating balloon (Teleported to body to escape stacking contexts) -->
    <Teleport to="body">
      <div
        ref="balloonRef"
        :class="balloonClasses"
        role="tooltip"
        aria-live="polite"
      >
        <!-- Top / Bottom: horizontal arrow row -->
        <template v-if="!isHorizontalPosition">
          <!-- Arrow appears between trigger and body. For 'top', body is above → arrow below.
               flex-direction handles order; we always render arrow first in DOM for a11y. -->
          <div :class="arrowRowClass">
            <svg
              class="bt-tooltip__arrow"
              :width="arrowWidth"
              :height="arrowHeight"
              :viewBox="arrowViewBox"
              fill="none"
              aria-hidden="true"
            >
              <path :d="arrowPath" fill="var(--bg-inverse)" />
            </svg>
          </div>
        </template>

        <!-- Left / Right: vertical arrow column -->
        <template v-if="isHorizontalPosition">
          <div :class="arrowColClass">
            <svg
              class="bt-tooltip__arrow"
              :width="arrowWidth"
              :height="arrowHeight"
              :viewBox="arrowViewBox"
              fill="none"
              aria-hidden="true"
            >
              <path :d="arrowPath" fill="var(--bg-inverse)" />
            </svg>
          </div>
        </template>

        <!-- Body -->
        <div class="bt-tooltip__body">
          <!-- Rich content slot overrides text prop -->
          <slot name="content">
            <p v-if="text" class="bt-tooltip__text">{{ text }}</p>
          </slot>
        </div>
      </div>
    </Teleport>
  </div>
</template>
